language: python
python:
  - "2.7"
  # - "3.4"
before_install:
  - sudo apt-get install bedtools
install:
  # packages for running tests
  - pip install setuptools
  - pip install flake8
  # packages specified by setup.py
  - pip install .
script:
  - flake8 . --exclude=.venv --ignore=E501
  - nosetests
